# Generated by Django 4.1.2 on 2022-11-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='category',
            field=models.CharField(choices=[('1', 'GEN'), ('2', 'SC'), ('3', 'ST'), ('4', 'OBC')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='father',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='mother',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='title',
            field=models.CharField(choices=[('1', 'Mrs.'), ('2', 'Mr.'), ('3', 'Dr.'), ('4', 'Ms.')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Nationality',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
