# Generated by Django 4.1.2 on 2022-11-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spez',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='spez_Req',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='restapi.spez'),
            preserve_default=False,
        ),
    ]
