# Generated by Django 4.1.2 on 2022-11-02 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_applicant_category_applicant_father_applicant_mother_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('age', models.PositiveBigIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Rather Not Say')], max_length=1, null=True)),
                ('title', models.CharField(choices=[('1', 'Mrs.'), ('2', 'Mr.'), ('3', 'Dr.'), ('4', 'Ms.')], max_length=5, null=True)),
                ('father', models.CharField(max_length=40, null=True)),
                ('mother', models.CharField(max_length=40, null=True)),
                ('category', models.CharField(choices=[('1', 'GEN'), ('2', 'SC'), ('3', 'ST'), ('4', 'OBC')], max_length=5, null=True)),
                ('Nationality', models.CharField(max_length=30, null=True)),
                ('qualifications', models.CharField(choices=[('1', 'B.A.'), ('2', 'B.Arch.'), ('3', 'BSc'), ('4', 'MSc'), ('5', 'B.Tech'), ('6', 'M.Tech'), ('7', 'PhD')], max_length=30, null=True)),
                ('cgpa', models.DecimalField(decimal_places=1, max_digits=2)),
                ('experiance', models.PositiveBigIntegerField()),
                ('citations', models.PositiveBigIntegerField()),
                ('publications', models.PositiveBigIntegerField()),
                ('country', models.CharField(max_length=40, null=True)),
                ('city', models.CharField(max_length=40, null=True)),
                ('state', models.CharField(max_length=40, null=True)),
                ('district', models.CharField(max_length=40, null=True)),
                ('postal', models.CharField(max_length=50, null=True)),
                ('pincode', models.CharField(max_length=6, null=True)),
                ('mob_num', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=45)),
                ('post', models.CharField(max_length=30)),
                ('cgpa_Req', models.DecimalField(decimal_places=1, max_digits=2)),
                ('phd_Req', models.BooleanField(default=False)),
                ('createdby', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='spez_Req',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='job_app',
            name='spez_Req',
        ),
        migrations.AddField(
            model_name='user',
            name='cce_Acess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='cse_Acess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='ece_Acess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hum_Acess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mec_Acess',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='admin',
        ),
        migrations.DeleteModel(
            name='applicant',
        ),
        migrations.DeleteModel(
            name='job_App',
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapi.job'),
        ),
        migrations.AddField(
            model_name='application',
            name='spez_Req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapi.spez'),
        ),
        migrations.AddField(
            model_name='user',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.application'),
        ),
    ]
