# Generated by Django 4.1.2 on 2022-11-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_spez_dept_alter_job_spez_req'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='spez_Req',
            new_name='spez',
        ),
    ]
