# Generated by Django 4.1.2 on 2022-11-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_rename_spez_req_application_spez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
