# Generated by Django 4.1.2 on 2022-11-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_alter_job_cgpa_req_alter_job_createdby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='phd_Req',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hum_Acess',
        ),
    ]
