# Generated by Django 4.1.2 on 2022-11-03 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_remove_user_application_application_hirescore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='dept_name',
        ),
        migrations.AddField(
            model_name='application',
            name='schedule',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.dept'),
        ),
    ]
