# Generated by Django 4.1.2 on 2022-11-03 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_dept_remove_job_dept_name_application_schedule_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dept',
            new_name='department',
        ),
    ]
