# Generated by Django 4.1.2 on 2022-11-03 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_rename_dept_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
