# Generated by Django 4.1.2 on 2022-11-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='phd_Req',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='roundNum',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='schedule',
            field=models.DateTimeField(null=True),
        ),
    ]
